[theme]
name = "gruvbox-dark"

[theme.overrides]
good_bg = "#2c6941"

[icons]
name = "awesome"

[[block]]
block = "music"
marquee_speed = 0.15
max_width = 20
buttons = []

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp1s0"
signal_strength = true
ssid = true
ip = false
speed_up = false
speed_down = false
graph_up = false
graph_down = false
interval = 5

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
